### ISSUE TITLE
How to send a tombstone via outbox?

### ISSUE THREAD

**Issue by mkjensen** [artembilan/microservices-patterns-spring-integration#1]
I have been looking into the [outbox](https://github.com/artembilan/microservices-patterns-spring-integration/blob/main/outbox/src/main/java/org/springframework/integration/microservices/outbox/OutboxApplication.java) sample.

The bottom line is that I do not understand how to get tombstones published to Kafka. I can create a `Message` with a `KafkaNull` payload, but when that message is serialized for `JdbcChannelMessageStore`, an exception is thrown: `NotSerializableException: org.springframework.kafka.support.KafkaNull`

I did note that the sample states:

> The business data must be Serializable since this is currently only a mechanism how Message<?> can be stored into INT_CHANNEL_MESSAGE table for RDBMS.

I tried circumventing that serialization by adding transformation to/from JSON before/after the queue using `JdbcChannelMessageStore`, but that then forces the addition of another queue for the polling to work which breaks the transactional setup.

I then, mostly just to convince myself that I could _hack_ it, added a custom header to the message (with some payload) to signal that it should be treated as a tombstone. I could then add a custom `ProducerRecordCreator` to the `KafkaProducerMessageHandlerSpec` that checks for the header and uses a `null` value.

What is the _right_ way to be able to send tombstones through an outbox?

**Comment by artembilan** [comment]
@mkjensen ,

thank you for looking into this repo!
We really appreciate your feedback.

We definitely can make that `org.springframework.kafka.support.KafkaNull` type as `Serializable`, but it is not clear how one would treat `KafkaNull` as "business data".
What kind of entity is that?
The pattern is about storing some entity and and then publish it as a message to interested parties.

Probably you just need a plain `Kafka.outboundChannelAdapter()` to send this `KafkaNull` manually?

> another queue for the polling

You don't need `QueueChannel` in between just for transformation. That can be plain `DirectChannel` and transformation will be a part of the current transaction.
so, if you'd like some immediate solution for your struggle, it may look like this as modification to that `Outbox.buildFlow()`:
```
.recipientFlow(messagingMiddleware -> messagingMiddleware
                                                                        .transform(Transformers.toJson())
									.channel(c -> c.queue(this.channelMessageStore, "outbox"))
                                                                        .transform(Transformers.fromJson())
									.handle(this.messagePublisherHandler,
											e -> e.poller(poller -> poller.fixedDelay(1000).transactional()))))
```

But again: I don't see that it is logical to have a `KafkaNull` as business data to be stored in the previous `businessDataHandler`.

**Comment by mkjensen** [comment]
@artembilan, thank you for your comment.

The `transform` additions around `channel` do not work because they break the polling:
> A poller should not be specified for endpoint 'outbox.subFlow#1.org.springframework.integration.config.ConsumerEndpointFactoryBean#2', since 'bean 'outbox.subFlow#1.channel#2'; defined in: 'org.springframework.integration.microservices.outbox.OutboxApplication'; from source: 'bean method outbox'' is a SubscribableChannel (not pollable).

Adding a new queue after the `fromJson` transform seems to break the transactional setup.

I can follow your point about `KafkaNull` not being business data. I wonder then how you would express the deletion of business data? I'm thinking normal CRUD operations where the delete would both remove data from a database and send a tombstone to Kafka.

I'm not sure whether this changes what I would need to do, but I'm including this in case it does. I used the sample as the basis for building something else. I wanted to introduce a generic setup of the outbox pattern so that multiple services could easily use it. Basically I have a class extending `IntegrationFlowAdapter` with a method looking something like this:
```
@Override
protected IntegrationFlowDefinition<?> buildFlow() {
  return from(outboxChannel)
      .channel(MessageChannels.queue(jdbcChannelMessageStore, groupId))
      .handle(
          Kafka.outboundChannelAdapter(kafkaTemplate),
          e -> e.poller(__ -> PollerFactory.fixedDelay(<snip>).transactional()));
}
```

I have a bean post processor that finds instances of a class with a `void schedule(K entityId, V event)` method and for each one creates the above flow where a unique `DirectChannel` (the `outboxChannel` above) is used to send messages. A `KafkaTemplate<K, V>` bean is available.

The `schedule` method is implemented like:
```
Message<V> message = MessageBuilder.withPayload(event)
    .setHeader(KafkaHeaders.KEY, entityId)
    .build();
outboxChannel.send(message);

if (event.getOperation() == Operation.DELETE) {
  Message<KafkaNull> tombstoneMessage = MessageBuilder.withPayload(KafkaNull.INSTANCE)
      .copyHeaders(message.getHeaders())
      .build();
  outboxChannel.send(tombstoneMessage);
}
```

It all seems to work nicely (also with the tests I created to convince myself that the transactional setup is correct) except for the tombstone as `KafkaNull` is not serializable. In other words, my challenge is this use case:

```
// Service class details omitted

@Transactional
public void delete(Entity entity) {
  // Do something with entity, probably just delete it in database.
  Event event = mapper.toEvent(entity).operation(Operation.DELETE);
  outbox.schedule(entity.getId(), event);
}
```

**Comment by mkjensen** [comment]
An additional comment regarding transforming to/from JSON. I tried adding custom serialization directly to `JdbcChannelMessageStore` and realized that it means that the IDs of the messages change. That results in logs like `WARN  o.s.i.j.s.JdbcChannelMessageStore -- Message with id 'fef0828f-5aec-ec1b-e86d-58cdeb49e6cf' was not deleted` so I guess it confuses the setup. I'm guessing this is why the default setup uses Java serialization - to keep the original IDs of messages.

Edit: I hacked this workaround but... is there maybe another/better way?

```
@Bean
JdbcChannelMessageStore jdbcChannelMessageStore(DataSource dataSource, ObjectMapper objectMapper) {
    JdbcChannelMessageStore jdbcChannelMessageStore = new JdbcChannelMessageStore(dataSource);
    jdbcChannelMessageStore.setChannelMessageStoreQueryProvider(new PostgresChannelMessageStoreQueryProvider());
    ObjectMapper copy = objectMapper.copy();
    copy.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
    Jackson2JsonObjectMapper jackson2JsonObjectMapper = new Jackson2JsonObjectMapper(copy);
    ObjectToJsonTransformer objectToJsonTransformer = new ObjectToJsonTransformer(jackson2JsonObjectMapper);
    MessageBuilderFactory messageBuilderFactory = new MutableMessageBuilderFactory();
    objectToJsonTransformer.setMessageBuilderFactory(messageBuilderFactory);
    JsonToObjectTransformer jsonToObjectTransformer = new JsonToObjectTransformer(jackson2JsonObjectMapper);
    jsonToObjectTransformer.setMessageBuilderFactory(messageBuilderFactory);
    jdbcChannelMessageStore.setSerializer(new Serializer<>() {

        private static final DefaultSerializer DEFAULT_SERIALIZER = new DefaultSerializer();

        @Override
        public void serialize(Message<?> object, OutputStream outputStream) throws IOException {
            Message<?> jsonMessage = objectToJsonTransformer.transform(object);
            DEFAULT_SERIALIZER.serialize(jsonMessage, outputStream);
        }
    });
    jdbcChannelMessageStore.setDeserializer(new Deserializer<>() {

        private static final DefaultDeserializer DEFAULT_DESERIALIZER = new DefaultDeserializer();

        @Override
        public Message<?> deserialize(InputStream inputStream) throws IOException {
            Message<?> jsonMessage = (Message<?>) DEFAULT_DESERIALIZER.deserialize(inputStream);
            return jsonToObjectTransformer.transform(jsonMessage);
        }
    });
    return jdbcChannelMessageStore;
}
```

**Comment by artembilan** [comment]
Thank you for sharing more info!

However I'd like to stop this dead-end discussion since Kafka tombstone is not what you are looking for.
See its reasoning in Apache Kafka specification: https://medium.com/@damienthomlutz/deleting-records-in-kafka-aka-tombstones-651114655a16
So, it does remove the record from the topic with same key.
But what we really need from the messaging middleware is to emit an event on the other side. Many other messaging brokers just really removes those consumed messages from their store.
So, for consumers of the outbox patterns it doesn't matter what broker is doing with the message: we just want to have an event to react respectively for an aggregator changes.

I'd prefer to have an event type as an aggregator property. In general solution it simply can be a header of message we are going to send to our business handler.

Either way, here is a fixed version of the sub-flow I suggested you before:
```
.recipientFlow(messagingMiddleware -> messagingMiddleware
                                                                        .transform(Transformers.toJson())
									.channel(c -> c.queue(this.channelMessageStore, "outbox"))
                                                                        .transform(Transformers.fromJson(),
                                                                                         e -> e.poller(poller -> poller.fixedDelay(1000).transactional()))
									.handle(this.messagePublisherHandler))
```
The point is that we have to use a `poller()` exactly on the endpoint which is going to consumer from a `QueueChannel`.

If you are going to use a JSON (de)serialization for a `JdbcChannelMessageStore`, then you must use a Jackson API directly.
Those `ObjectToJsonTransformer` and `JsonToObjectTransformer` definitely create new `Message` instances after their process which indeed leads to new ids and so on with extra performance degradation.

I'm closing this as `Invalid` since the question does not fit into Outbox pattern logic.

Please, consider net time to ask questions on StackOverflow.
